#!/usr/bin/env bash

set -e # exit on error
set -u # error on undefined var
set -o pipefail # exit on command pipe failure

# Set working dir to script location
cd "$(dirname "$0")"

# Hardcoded mapping of source to destination files
declare -A file_map
file_map["../docs/src/Readme.lhs"]="../README.md"

# NOTE:
# We use the extension `+lhs` to enable support for Literate Haskell
#     https://pandoc.org/demo/example33/7.5-literate-haskell-support.html
# We use `-smart` to disable smart punctuation (curly quotes, en-dashes, etc.)
#     https://pandoc.org/demo/example33/7.1-typography.html
#
#
# List of supported extensions:
#     pandoc --list-extensions=markdown
for from in "${!file_map[@]}"; do
    to="${file_map[$from]}"
    echo "Converting $from -> $to"
    pandoc \
        --standalone \
        "$from" \
        -o "$to" \
        --from markdown+lhs-smart --to gfm


    # Add a header to the generated file markdown file.
    src_display="${from#../}"
    tmp_file="$(mktemp)"
    {
        printf '<!--\n'
        printf '    DO NOT EDIT THIS FILE.\n\n'
        printf '    This file was generated from `%s`.\n' "$src_display"
        printf '    Edit that file, and then run `just pandoc`.\n'
        printf '%s\n\n' '-->'
        cat "$to"
    } > "$tmp_file"
    mv "$tmp_file" "$to"
done
