#!/usr/bin/env bash

set -e # exit on error
set -u # error on undefined var
set -o pipefail # exit on command pipe failure

# Set working dir to script location
cd "$(dirname "$0")"

# Hardcoded mapping of source to destination files
declare -A file_map
file_map["../docs/src/Readme.lhs"]="../README.md"

# NOTE:
# We use the extension `+lhs` to enable support for Literate Haskell
#     https://pandoc.org/demo/example33/7.5-literate-haskell-support.html
# We use `-smart` to disable smart punctuation (curly quotes, en-dashes, etc.)
#     https://pandoc.org/demo/example33/7.1-typography.html
#
#
# List of supported extensions:
#     pandoc --list-extensions=markdown

# Replaces lines matching `@include:SomeFile.lhs@` with the pandoc-converted
# markdown of that file. This lets Readme.lhs embed separate LHS modules
# (each with their own imports) without import conflicts in a single module.
#
# I implemented this "include" system to work around some LHS limitations:
#   * you can't mix "imports" in between code blocks.
#   * you can't import two different modules qualified with the same name.
process_includes() {
    local src_dir="$1"
    while IFS= read -r line; do
        if [[ "$line" =~ ^@include:(.+\.lhs)@$ ]]; then
            included="${BASH_REMATCH[1]}"
            if [[ ! -f "$src_dir/$included" ]]; then
                echo "Error: included file '$src_dir/$included' does not exist" >&2
                exit 1
            fi
            pandoc \
                "$src_dir/$included" \
                --from markdown+lhs-smart --to gfm
        else
            printf '%s\n' "$line"
        fi
    done
}

for from in "${!file_map[@]}"; do
    to="${file_map[$from]}"
    echo "Converting $from -> $to"

    # Add a header to the generated file markdown file.
    src_dir="$(dirname "$from")"
    src_display="${from#../}"
    tmp_file="$(mktemp)"

    {
        printf '<!--\n'
        printf '    DO NOT EDIT THIS FILE.\n\n'
        printf '    This file was generated from `%s`.\n' "$src_display"
        printf '    Edit that file, and then run `just pandoc`.\n'
        printf '%s\n\n' '-->'
        pandoc \
            --standalone \
            "$from" \
            --from markdown+lhs-smart --to gfm | \
        process_includes "$src_dir"
    } > "$tmp_file"

    mv "$tmp_file" "$to"
done
